<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>23° - Astral Finder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
	<link href="<?=base_url();?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=base_url();?>css/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="<?=base_url();?>css/23deg.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
	
	

	<script type="text/javascript" src="<?=base_url();?>js/jquery.min.js"></script>
	<script type="text/javascript" src="<?=base_url();?>js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?=base_url();?>js/holder.js"></script>

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>
	<div class="band band-header">
		<div id="header" class="container">
			<ul id="main_nav">
				<li class="active"><a href="#">Inicio</a></li>
                <li><a href="#get_the_app">Mobile App</a></li>
                <li><a href="#this_is_the_api">API</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#whats_skymorph">What's SkyMorph?</a></li>
                <li><a href="#this_is_the_team">Our Team</a></li>
			</ul>
			<img id="logo" src="<?=base_url();?>img/23deg_logo.png" alt="23 degree">
		</div>
	</div>

	<div class="container marketing">
		
		<ul class="nav nav-tabs">
			<li class="active"><a href="#tab1" data-toggle="tab">Mapa</a></li>
			<!--<li><a href="#tab2" data-toggle="tab">Usuarios avanzados</a></li>-->
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="tab1">
				<div class="row">
					<div class="span8">
						<div id="map_canvas"></div>
					</div>
					<div class="span4">
						<div id="image_container">
							<img id="space_image" src="#" />
						</div>
					</div>
				</div>
			</div>
			<!--<div class="tab-pane active" id="tab2">-->
			<!--	hola-->
			<!--</div>-->
		</div>
		
	
	
	<!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div id="get_the_app" class="featurette">
        <!--<img class="featurette-image pull-right" src="<?=base_url();?>img/mobile_app.png">-->
        <h2 class="featurette-heading">Mobile App. <span class="muted">The story of space, in your hands!</span></h2>
        <p class="lead"><strong><a href="<?=base_url();?>files/23_degree.apk">Download our App for Android.</a></strong></p>
      </div>

      <hr class="featurette-divider">

      <div id="this_is_the_api" class="featurette">
        <h2 class="featurette-heading">API. <span class="muted">Build applications using SkyMorph!</span></h2>
        <p class="lead">An easy RESTful API for SkyMorph.</p>
      </div>

      <hr class="featurette-divider">

      <div id="about" class="featurette">
        <h2 class="featurette-heading">About 23 degrees. <span class="muted">A friendlier access to SkyMorph!</span></h2>
        <p class="lead">
			23° provides a user-friendly access SkyMorph Imagery.<br />
			- RESTfull API for SkyMorph.<br />
			- Android app to search the data and display the resulting images.<br />
			- Searching by position using GPS coordenates of the smartphone.<br />
		</p>
      </div>

      <hr class="featurette-divider">

      <div id="whats_skymorph" class="featurette">
        <h2 class="featurette-heading">What's SkyMorph?. <span class="muted">Space as a movie.</span></h2>
        <p class="lead">
			Have you ever wonder about all the asteroids, comets, planets or stars around you?
			Just take a picture of the sky, and 23° will collect the exact image taken in the coordinates using images from SkyMorph.
			SkyMorph provides access to optical images and catalogs generated by the Near Earth Asteroid Tracking (NEAT) program. It provides access to imagery by time and position or searching by specific asteroid or other moving object. The time dimension, unique to SkyMorph, allows you to discover changes in the intensities of stars, e.g. supernovae, or to discover moving objects, e.g. comets.
		</p>
      </div>
	  
      <hr class="featurette-divider">

      <div id="this_is_the_team" class="featurette">
        <h2 class="featurette-heading">Our team. <span class="muted"></span></h2>
        <p class="lead"><br />
			Viviana Garrido- capitan and comandrer of the Apollo XX mision<br />
			@little_pheonix<br /><br />
			Jaime Acevedo-A.I. develpoer for Curiosity<br />
			@jaimeacevedo<br /><br /><br />
			Mauro Trigo -NASA official hacker<br />
			@maurotrigo<br /><br /><br />
			Sergio Del Río-Guru and space evangelist<br />
			@sergiodelrio
		</p>
      </div>
	
		<hr class="featurette-divider">
      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2013 El número 23 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->
	
	<?php $this->load->view('map'); ?>
  </body>
</html>
